---
title: "Differences Between the JS Repo"
output: rmarkdown::html_vignette
vignette: >
  %\VignetteIndexEntry{Differences Between the JS Repo}
  %\VignetteEngine{knitr::rmarkdown}
  %\VignetteEncoding{UTF-8}
---

```{r, include = FALSE}
knitr::opts_chunk$set(
  collapse = TRUE,
  comment = "#>"
)
```

There are a handful of differences between the JavaScript repository. Below is a list of these differences.

1. Non capturing groups are not used by default. Instead of `(?:)`, we use `()` because non-capture groups do not support back referencing whereas capture groups do. See [here](http://www.manifold.net/doc/radian/why_do_non-capture_groups_exist_.htm) for more information on why this decision was made.
2. Lookarounds are supported. This is just a nice feature to have.
3. The function `then` is not included because it's an alias and clashes with how the pipe operator is often pronounced "then".
4. In a similar not, aliases in general are not included because I want the number of functions to be as minimal as possible.
5. The function `add` is not included because the pipe is used instead.
6. The function `replace` is not included because there are R functions already designed for this purpose.
7. The function `or` is excluded in favor of `rx_either_of`.
8. Function names are prefixed with `rx_` for convenience and avoiding namespace collisions. 

